---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trivy-extractor
spec:
  selector:
    matchLabels:
      app: trivy-extractor
  endpoints:
    - interval: 15s
      port: web
      scrapeTimeout: 14s
  namespaceSelector:
    matchNames:
      - trivy-operator